opticharger: Add pngquant
* pngquant is a command-line utility and a library for converting 24/32-bit PNG images to paletted (8-bit) PNGs.

The conversion reduces file sizes significantly (often as much as 70%) and preserves full alpha transparency. Generated images are compatible with all modern web browsers, and have better fallback in IE6 than 24-bit PNGs.

Read more info at http://pngquant.org/

From my tests the overall compression reduces final flashable zips by 7-10 MBs.  The reduction of quality in pngs is also still slight enough as to avoid detection.

Signed-off-by: Chester Kener <Cl3Kener@gmail.com>

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Super-mega opticharger of doom
+# Super-mega LiquidSmooth opticharger of doom
 # Shrinks apks by running pngcrush or optipng or pngout on png images
 #
 # Point APKCERTS at the full path to a generated apkcerts.txt file
@@ -13,6 +13,8 @@ QUIET=1
 BASE=`pwd`
 BRUTECRUSH="-brute"
 TMPDIR=/tmp/opticharge-$$
+NINEPATCH=0
+
 . $ANDROID_BUILD_TOP/vendor/liquid/tools/functions
 
 if [ -z "$BRUTE_PNGCRUSH" ]
@@ -31,21 +33,26 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
+        echo -e $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
+    echo -e $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
 fi
 
-if [ "$(which pngcrush)" != "" ];
+if [ "$(which pngquant)" != "" ];
+then
+    optimize_png () {
+        pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null
+    }
+elif [ "$(which pngcrush)" != "" ];
 then
     optimize_png () {
         pngcrush -q ${BRUTECRUSH} $1 ${1}.out 1> /dev/null 2> /dev/null
-        mv ${1}.out ${1}
+        mv ${1}.out ${1} 2> /dev/null
     }
 elif [ "$(which optipng)" != "" ];
 then
@@ -63,26 +70,26 @@ then
         pngout $1
     }
 else
-    echo $CL_RED"Please install pngcrush, optipng, or pngout"$CL_RST
+    echo -e $CL_RED"Please install pngquant, pngcrush, optipng, or pngout"$CL_RST
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
+    echo -e $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
+    echo -e $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo $CL_CYN"Optimize:"$CL_RST" $NAME..";
+    echo -e $CL_CYN"Optimize:"$CL_RST" $NAME..";
 
     if [ "$2" != "" ];
     then
@@ -90,7 +97,7 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo $CL_RED"$CERT does not exist!"$CL_RST;
+            echo -e $CL_RED"$CERT does not exist!"$CL_RST;
             exit 1;
         fi
     else
@@ -98,45 +105,50 @@ then
         [ $QUIET ] || echo "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo $CL_RED"No apk info for $NAME"$CL_RST;
+            echo -e $CL_RED"No apk info for $NAME"$CL_RST;
             exit 1;
         fi
         CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
         KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo $CL_RED"Unable to find certificate for $NAME"$CL_RST
+            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo $CL_CYN"$NAME is presigned, skipping"$CL_RST
+            echo -e $CL_CYN"$NAME is presigned, skipping"$CL_RST
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo $CL_CYN"Certificate:"$CL_RST" $CERT";
+    [ $QUIET ] || echo -e $CL_CYN"Certificate:"$CL_RST" $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
     trap "rm -rf $TMPDIR; exit" INT TERM EXIT
     cd $TMPDIR/$NAME
     unzip -q $BASE/$1
-    for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
+    if [ "$NINEPATCH" = "1" ]; then
+        PNG_FILES=`find . -name "*.png" | tr "\n" " "`
+    else
+        PNG_FILES=`find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
+    fi
+    for x in $PNG_FILES
     do
-        [ $QUIET ] || echo $CL_CYN"Crushing $x"$CL_RST
+        [ $QUIET ] || echo -e $CL_CYN"Crushing $x"$CL_RST
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo $CL_CYN"Repacking apk.."$CL_RST
+    [ $QUIET ] || echo -e $CL_CYN"Repacking apk.."$CL_RST
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
-    
-    [ $QUIET ] || echo $CL_CYN"Resigning with cert: `echo $CERT`"$CL_RST
+
+    [ $QUIET ] || echo -e $CL_CYN"Resigning with cert: `echo $CERT`"$CL_RST
 
     [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo $CL_CYN"Zipaligning.."$CL_RST
+    [ $QUIET ] || echo -e $CL_CYN"Zipaligning.."$CL_RST
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
