Setup for Lollipop
Change-Id: Ia84e6bb70c55eaa48b1ac864264179aa64e6a1f9

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -1,13 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Super-mega opticharger of doom
-# Shrinks apks by running pngcrush or optipng or pngout on png images
+# Super-mega LiquidSmooth opticharger of doom
+# Shrinks apks by running pngquant or pngcrush or optipng or pngout on png images
 #
-# Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
-# /home/shade/dev/sources/android-cm-eclair/out/target/product/dream_sapphire/obj/PACKAGING/target_files_intermediates/cyanogen_dream_sapphire-target_files-eng.shade/META/apkcerts.txt
-#
-# cyanogen - shade@chemlab.org
-# ChrisSoyars - me@ctso.me
+
+. $ANDROID_BUILD_TOP/vendor/liquid/tools/colors
+
+OUT_TARGET_HOST=$(uname -a | grep Darwin)
+if [ -z "$OUT_TARGET_HOST" ]
+then
+    OUT_TARGET_HOST=linux-x86
+else
+    OUT_TARGET_HOST=darwin-x86
+fi
 
 set -e
 QUIET=1
@@ -31,21 +36,26 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo "Set APKCERTS to the path to your apkcerts.txt file"
+        echo -e ${red}"Set APKCERTS to the path to your apkcerts.txt file"${txtrst}
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo "Invalid path to apkcerts.txt, set APKCERTS to the correct path."
+    echo -e ${red}"Invalid path to apkcerts.txt, set APKCERTS to the correct path."${txtrst}
 fi
 
-if [ "$(which pngcrush)" != "" ];
+if [ "$(which pngquant)" != "" ];
+then
+    optimize_png () {
+        pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null
+    }
+elif [ "$(which pngcrush)" != "" ];
 then
     optimize_png () {
         pngcrush -q ${BRUTECRUSH} $1 ${1}.out 1> /dev/null 2> /dev/null
-        mv ${1}.out ${1}
+        mv ${1}.out ${1} 2> /dev/null
     }
 elif [ "$(which optipng)" != "" ];
 then
@@ -63,59 +73,64 @@ then
         pngout $1
     }
 else
-    echo "Please install pngcrush, optipng, or pngout"
+    echo -e ${red}"Please install pngquant, pngcrush, optipng, or pngout"${txtrst}
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo "Please ensure aapt is in your \$PATH"
+    echo -e ${red}"Please ensure aapt is in your \$PATH"${txtrst}
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo "Please ensure zipalign is in your \$PATH"
+    echo -e ${red}"Please ensure zipalign is in your \$PATH"${txtrst}
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo "Optimizing $NAME...";
+    echo -e ${bldgrn}"Optimizing:${txtrst} $NAME...";
 
     if [ "$2" != "" ];
     then
-        CERT=build/target/product/security/$2.x509.pem
-        KEY=build/target/product/security/$2.pk8
+        if [ "$DEFAULT_SYSTEM_DEV_CERTIFICATE" ]; then
+            CERT_PATH=`dirname $DEFAULT_SYSTEM_DEV_CERTIFICATE`
+        else
+            CERT_PATH=build/target/product/security
+        fi
+        CERT="$CERT_PATH"/$2.x509.pem
+        KEY="$CERT_PATH"/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo "$CERT does not exist!";
+            echo -e ${red}"$CERT does not exist!"${txtrst};
             exit 1;
         fi
     else
         APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
-        [ $QUIET ] || echo "APKINFO: $APKINFO";
+        [ $QUIET ] || echo -e "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo "No apk info for $NAME";
+            echo -e ${red}"No apk info for $NAME"${txtrst};
             exit 1;
         fi
-        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
-        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
+        CERT=`echo -e $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
+        KEY=`echo -e $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo "Unable to find certificate for $NAME"
+            echo -e ${red}"Unable to find certificate for $NAME"${txtrst}
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo "$NAME is presigned, skipping"
+            echo -e ${cya}"$NAME is presigned, skipping"${txtrst}
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo "Certificate: $CERT";
+    [ $QUIET ] || echo -e ${bldylw}"Certificate:${txtrst} $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -124,19 +139,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo "Crushing $x"
+        [ $QUIET ] || echo -e ${bldgrn}"Crushing${txtrst} $x"
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo "Repacking apk.."
+    [ $QUIET ] || echo -e ${bldgrn}"Repacking apk.."${txtrst}
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
-    
-    [ $QUIET ] || echo "Resigning with cert: `echo $CERT`"
+
+    [ $QUIET ] || echo -e ${bldgrn}"Resigning with cert:${txtrst} `echo -e $CERT`"
 
     [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo "Zipalign.."
+    [ $QUIET ] || echo -e ${bldgrn}"Zipalign.."${txtrst}
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
@@ -144,6 +159,6 @@ then
     fi
     rm $BASE/$1.old
 else
-    echo "Usage: $0 [apk file]"
+    echo -e "Usage: $0 [apk file]"
 fi
 
